#This is a basisc workflow to healp you get started with actions 

name: CI

#Controls when the workflow will run 
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

#Allows you to run this workflow manually from the actions tab 

  workflow_dispatch:
jobs:
  build:
  
    runs-on: ubuntu-lastest #,windows-latest, macos

    steps: 
      - uses: actions/checkout@v3

      - name: Run a one-line script 
        run: echo Hello, world!
    
      - name: Run a multi-line script 
        run: |
          echo Add other actios to build, 
          echo test, and deploy your project. 
          




#A workflow run is made up of one or more jobs that can run sequentially in parallel 

  
